language: node_js

node_js:
  - 12

sudo: false

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn global add serverless
  - yarn

env:
  - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
  - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

jobs:
  include:
    - stage: lint
      script: yarn lint
    - stage: deploy
      script: sls deploy
