name: deploy to AWS lambda by sls
on:
  push:
    branches: master

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with: 
        node-version: ${{ matrix.node-version }}
      
    - name: Install Dependencies
      run: |
        yarn global add serverless
        yarn

    - name: Deploy to lambda
      run: sls deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

    - name: Notify status to slack
      uses: homoluctus/slatify@master
      if: always()
      with:
        type: ${{ job.status }}
        job_name: '*Deploy Status*'
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
